server:
  port: 0
spring:
  application:
    name: auth-service
  r2dbc:
    username: admin
    password: admin
    url: r2dbc:postgresql://localhost:5433/auth-service
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5433/auth-service
    user: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

apiGatewayAddress: http://localhost:8082
