server:
  port: 8084
spring:
  application:
    name: auth-service
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5433/auth-service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

apiGatewayAddress: http://localhost:8082

jwt:
  token:
    life_expectancy: 86400
    secret: ZheltiyPolosatik123ZheltiyPolosatik123